### ISSUE TITLE
Not receiving JWT Token 

### ISSUE THREAD

**Issue by Uny1me** [co-cart/cocart-jwt-authentication#1]
I have this plugin installed and when i make a request to the login endpoint i just receive user details but no token.

the login endpoint i am using is https://sample-site.com/wp-json/cocart/v2/login

sample response :

`{
    "user_id": "5544",
    "first_name": "Johann",
    "last_name": "Strauss",
    "display_name": "Johann Libert",
    "role": "Customer",
    "avatar_urls": {
        "24": "https://secure.gravatar.com/avatar/5d16ff7074e8314350305a1e7ac5f055?s=24&d=mm&r=g",
        "48": "https://secure.gravatar.com/avatar/5d16ff7074e8314350305a1e7ac5f055?s=48&d=mm&r=g",
        "96": "https://secure.gravatar.com/avatar/5d16ff7074e8314350305a1e7ac5f055?s=96&d=mm&r=g"
    },
    "email": "cornellkid2@gmail.com",
    "extras": [],
    "dev_note": "Don't forget to store the users login information in order to authenticate all other routes with CoCart."
}`

**Comment by seb86** [comment]
@Uny1me  Can I take it that it did return and you made a mistake reporting the bug?

**Comment by Uny1me** [comment]
Yes apologies, also making the switch to cocart JWT has been massively helpful for flow. Thanks @seb86
